export const eventItems = [
    { id: 1, image: '/event/event1.jpeg', desc: '' },
    { id: 2, image: '/event/event2.jpeg', desc: '' },
    { id: 3, image: '/event/event3.jpeg', desc: '' },
    { id: 4, image: '/event/event4.jpeg', desc: '' },
    { id: 5, image: '/event/event5.jpeg', desc: '' },
    { id: 6, image: '/event/event6.jpeg', desc: '' },
    { id: 7, image: '/event/event7.jpeg', desc: '' },
    { id: 8, image: '/event/event8.jpeg', desc: '' },
    { id: 9, image: '/event/event9.jpeg', desc: '' },
    { id: 10, image: '/event/event10.jpeg', desc: '' },
    { id: 11, image: '/event/event11.jpeg', desc: '' },
    { id: 12, image: '/event/event12.jpeg', desc: '' },
    { id: 13, image: '/event/event13.jpeg', desc: '' },
    { id: 14, image: '/event/event14.jpeg', desc: '' },
    { id: 15, image: '/event/event15.jpeg', desc: '' },
    { id: 16, image: '/event/event16.jpeg', desc: '' },
    { id: 17, image: '/event/event17.jpeg', desc: '' },
    { id: 18, image: '/event/event18.jpeg', desc: '' },
    { id: 19, image: '/event/event19.jpeg', desc: '' },
    { id: 20, image: '/event/event20.jpeg', desc: '' },
    { id: 21, image: '/event/event21.jpeg', desc: '' },
    { id: 22, image: '/event/event22.jpeg', desc: '' },
    { id: 23, image: '/event/event23.jpeg', desc: '' },
    { id: 24, image: '/event/event24.jpeg', desc: '' },
    { id: 25, image: '/event/event25.jpeg', desc: '' },
    { id: 26, image: '/event/event26.jpeg', desc: '' },
    { id: 27, image: '/event/event27.jpeg', desc: '' },
    { id: 28, image: '/event/event28.jpeg', desc: '' },
    { id: 29, image: '/event/event29.jpeg', desc: '' },
    { id: 30, image: '/event/event30.jpeg', desc: '' },
    { id:31,  image: '/event/event31.jpeg', desc: ''},
    { id:32,  image: '/event/event32.jpeg', desc: ''},
  ];